### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by xuv** [01010101/AppleCronPrank#1]
Nice project. 
If you came up with this idea following [this tweet](https://twitter.com/hellocatfood/status/695605824815788033), it would be cool to give some credit back.

**Comment by 01010101** [comment]
Thx. Was thinking about doing a video and credit Antonio in it but totally
forgot about doing it on Github. Thx for the reminder Julien.

**Comment by xuv** [comment]
:) Your welcome. Looking forward for the video.
